### ISSUE TITLE
Some missing info into the doc for building image locally

### ISSUE THREAD

**Issue by pacospace** [AICoE/s2i-custom-notebook#11] opened 2020-06-05 07:12 UTC
**Is your feature request related to a problem? Please describe.**
If I'm a new user of the s2i-custom-notebook and I try to build my image locally using the command listed in the doc I don't see mention about:

- install s2i (which might be assumed, but some users do not have it installed by default, therefore a little guide there would be nice)

-  simply running command `s2i build . quay.io/thoth-station/s2i-custom-notebook:latest test:latest`  gives the following error:            
```
FATAL: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
Also after starting the deamon... there are docker issues. Maybe worth adding few words about s2i using `docker` as base.

Maybe a better soluton is to add some alternative description using `podman/buildah`. it would be nice.

**Comment by 4n4nd** [comment] 2020-06-05 13:21
This error might mean the `Docker` service is not running.

But I think I get the point here, we need more instructions introducing `s2i` and image building stuff.

**Comment by pacospace** [comment] 2020-06-05 13:23
> This error might mean the `Docker` service is not running.
> 
> But I think I get the point here, we need more instructions introducing `s2i` and image building stuff.

Yes the error is the Docker Deamon not running, but is more to have a general doc for the command. Thanks @4n4nd

**Comment by SankBad** [comment] 2020-09-23 15:57
Is there any update on this issue?
I am  trying to install s2i.

When I am running the command:
`$ go get github.com/openshift/source-to-image/cmd/s2i`

I am getting the error:

```
Package devmapper was not found in the pkg-config search path.
Perhaps you should add the directory containing devmapper.pc
to the PKG_CONFIG_PATH environment variable
Package 'devmapper', required by 'virtual:world', not found
pkg-config: exit status 1
# github.com/openshift/source-to-image/vendor/github.com/containers/storage/drivers/btrfs
go/src/github.com/openshift/source-to-image/vendor/github.com/containers/storage/drivers/btrfs/btrfs.go:8:10: fatal error: btrfs/ioctl.h: No such file or directory
 #include <btrfs/ioctl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
```


@4n4nd @harshad16 

I am using RHEL 8

**Comment by harshad16** [comment] 2020-09-23 16:20
> Is there any update on this issue?
> I am trying to install s2i.
> 
> When I am running the command:
> `$ go get github.com/openshift/source-to-image/cmd/s2i`

Did you try installation via available tar for Linux system. https://github.com/openshift/source-to-image#for-linux
if the issue is happening in the installation via go. 
may be pointing the question to https://github.com/openshift/source-to-image might be helpful.


About the issue of updating doc for the build, it for the non-root user using s2i directly with docker.
docker deamon is to be set to have this configuration fixed.
will updated the docs for this.

**Comment by SankBad** [comment] 2020-09-23 16:54
Thanks @4n4nd @harshad16 installation using tar is working.

**Comment by MichaelClifford** [comment] 2020-09-28 14:34
PR #36 adds some additional documentation about local builds that I think should address this issue.

**Comment by harshad16** [comment] 2020-09-29 11:48
Thanks @MichaelClifford  for the updates.

**Comment by harshad16** [comment] 2020-09-29 11:51
Seems like with commit from @MichaelClifford  it covers the setup and build with s2i concept. 
Closing this issue, Please re-open a new issue if needed.

**Closed as completed by harshad16** 2020-09-29 11:51 UTC
