### ISSUE TITLE
New minor release

### ISSUE THREAD

**Issue by tumido** [AICoE/s2i-custom-notebook#19] opened 2020-06-30 14:29 UTC
Hey, Kebechet!

Create a new minor release, please.

I need to build an image with https://github.com/AICoE/s2i-custom-notebook/pull/15 changes baked in. We need to rebuild and release new builder image version to achieve that.

**Comment by tumido** [comment] 2020-06-30 14:32
@4n4nd because of the https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis/pull/3

**Comment by goern** [comment] 2020-06-30 14:33
@saisankargochhayat please monitor this and let me know if you see and Tekton/Prow/Kebechet related issues. thx!

**Comment by goern** [comment] 2020-06-30 14:33
@harshad16

**Comment by 4n4nd** [comment] 2020-06-30 14:34
the build might not trigger since @tumido is not in the codeowners list

**Comment by harshad16** [comment] 2020-06-30 14:42
@tumido  @4n4nd @goern 
thank for opening the issue, the issue is in right direction.
as @4n4nd  stated this issue would not be addressed by kebechet, as @tumido  is not a maintainer.
however, none of this issue would be handle as the `.thoth.yaml` the file is missing which containers kebechet maintainer for this repo.
i will add required files and apps for kebechet to assist with this. 

Also only a maintainer can ask kebechet to release the application as we dont want to users to spam issue for kebechet to resolve.

**Comment by 4n4nd** [comment] 2020-06-30 14:43
oh lol

**Comment by saisankargochhayat** [comment] 2020-06-30 15:30
@tumido @4n4nd 
Please add a version string in a `version.py` file or any of the other options available in the documentation similar to - [link](https://github.com/thoth-station/thamos/blob/82b1cf02809f278f5b440575802457625a292986/thamos/__init__.py#L21)
Documentation - https://github.com/thoth-station/kebechet/tree/master/kebechet/managers/version

**Comment by harshad16** [comment] 2020-06-30 15:57
@saisankargochhayat  is the version.py a requirement for kebechet ?

**Comment by saisankargochhayat** [comment] 2020-06-30 16:14
> @saisankargochhayat is the version.py a requirement for kebechet ?

The version string should be any of the files mentioned in the documentation i.e. 
A requirement to make this manager operational is that your version should be stated as a string in your `setup.py`,` version.py` `__about__.py` or `__init__.py` file in a variable named `__version__`.

**Closed as completed** 2020-06-30 16:17 UTC
